### ISSUE TITLE
When training the network, are the backbone parameters frozen?

### ISSUE THREAD

**Issue by DUT-CSJ** [caoql98/SDM#10]
Hello, thank for sharing your great work.
I wanna know when training the network, are the backbone parameters frozen?
It seems the parameters of the backbone will be updated.
Look forward to your reply!

**Comment by caoql98** [comment]
Yes, since previous pre-trained models are relied on the natural images, we tend to also train the backbone's parameters.

**Comment by DUT-CSJ** [comment]
Thank you for your reply!
