### ISSUE TITLE
No NetworkInNetwork.py

### ISSUE THREAD

**Issue by wangshouxu** [caoql98/SDM#5]
Thanks for your work! But it has no NetworkInNetwork.py

  File "D:/SDM/train.py", line 17, in <module>
    from networks import *
  File "D:\SDM\networks\resnet50_34.py", line 7, in <module>
    from models.backbone import NetworkInNetwork as modeln
ImportError: cannot import name 'NetworkInNetwork' from 'models.backbone' (unknown location)

**Comment by caoql98** [comment]
Thanks for your attention! We do not need this module, I have deleted this and fix the bug
