### ISSUE TITLE
fail to run FPMMs_vgg

### ISSUE THREAD

**Issue by linhanwang** [caoql98/SDM#7]
Thanks for your brilliant work. I run the FPMMs successfully following default settings. But I failed to run FPMMs_vgg. 

Traceback (most recent call last):
  File "train.py", line 135, in <module>
    train(args)
  File "train.py", line 106, in train
    logits = model.forward_5shot(query_img, support_img, support_mask,query_mask)
  File "/home/linhan/projects/SDM/networks/FPMMs_vgg.py", line 127, in forward_5shot
    exit_feat_in_ = self.f_v_concate(query_feature, vec, feature_size)
  File "/home/linhan/projects/SDM/networks/FPMMs_vgg.py", line 146, in f_v_concate
    fea_pos = vec_pos.expand(-1, -1, feature_size[0], feature_size[1])  # tile for cat
RuntimeError: The expanded size of the tensor (41) must match the existing size (256) at non-singleton dimension 3.  Target sizes: [-1, -1, 41, 41].  Tensor sizes: [3, 256]

Could you please give me some hints?

**Comment by caoql98** [comment]
Hello， you could utilize tensor. unsqueeze(-1).unsqueeze(-1) firstly to make it have the same feature dimension.

**Comment by linhanwang** [comment]
Thanks so much for the suggestion. I will try it later.
