### ISSUE TITLE
Experiment on my own dataset

### ISSUE THREAD

**Issue by hhzxy** [caoql98/SDM#8]
If I want to run my dataset, there are only 4 categories, how do I get data_list and what parts do I need to pay attention to changing? Looking forward to your reply, thank you

**Comment by caoql98** [comment]
Thanks for your attention! Sorry, I write my own-designed codes to generate the data_list. I directly compute whether the images contain the objects in the target category. If so, the name of images would be added into the list.

**Comment by hhzxy** [comment]
Can you share it with me if it's convenient? My WeChat ID is xjdbaq521

发自我的iPhone


------------------ Original ------------------
From: caoql98 ***@***.***&gt;
Date: Sun,Jun 25,2023 9:45 PM
To: caoql98/SDM ***@***.***&gt;
Cc: hhzxy ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [caoql98/SDM] Experiment on my own dataset (Issue #8)





 
Thanks for your attention! Sorry, I write my own-designed codes to generate the data_list. I directly compute whether the images contain the objects in the target category. If so, the name of images would be added into the list.
